### ISSUE TITLE
Why Open Lighting Console need SDK version of runtime?

### ISSUE THREAD

**Issue by ghost** [flathub/com.github.mikacousin.olc#20]
While exploring [Flathub statistics](https://flathub.org/statistics), I noticed that the majority of GNOME apps use `org.gnome.Platform`, while minority of apps use `org.gnome.Sdk`.

Do Open Lighting Console really need SDK version? 

https://github.com/flathub/com.github.mikacousin.olc/blob/master/com.github.mikacousin.olc.json#L3-L5

For comparison

https://github.com/flathub/org.gnome.Calendar/blob/master/org.gnome.Calendar.json#L3-L5

Thanks.

**Comment by mikacousin** [comment]
Good point!
I think it comes from the model I used initially.
I'll take a closer look soon.

Thanks a lot.

**Comment by mikacousin** [comment]
olc now uses org.gnome.Platform

Thanks again !
