### ISSUE TITLE
olad/OlaServer.cpp:280: Failed to start the HTTP server.

### ISSUE THREAD

**Issue by luzidd** [flathub/com.github.mikacousin.olc#3]
Executing `flatpak run com.github.mikacousin.olc` results in
`olad/OlaServer.cpp:280: Failed to start the HTTP server.`

```
$ flatpak info com.github.mikacousin.olc

Open Lighting Console - Control your lighting shows

          ID: com.github.mikacousin.olc
         Ref: app/com.github.mikacousin.olc/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.5.1.beta
     License: GPL-3.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 33.5 MB
     Runtime: org.gnome.Sdk/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: f5a35b74e076138ce6433f6d1b2bb425158c576cb3b455c040e60f1019ce12cb
      Parent: 561252e02d5630768debf5881db45f73e27f0764d2820e397454e961e398ea88
     Subject: Try to embed a newer version of ola (d64eb89b)
        Date: 2022-08-20 20:05:00 +0000
```

I'm running Fedora Silverblue/Kinoite

**Comment by luzidd** [comment]
The error was on my side.
I was already running cockpit on port 9090, so when olad wanted to start it couldn't bind the port.
Maybe it would be benefitial if there was a check if the port is already in use or make the port cutomizable.

**Comment by mikacousin** [comment]
Thanks for the bug report. I will look at this as soon as possible.

**Comment by mikacousin** [comment]
You can install and test git version of olc if you want. Otherwise, I will update the flathub version when I have advanced the work in progress.
Thank you very much for your report.
I'm closing this issue for now, you can open it again if needed.
